Models/Genre.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace MelodyMusicLibrary.Models
{
    public class Genre
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public ICollection<AlbumGenre> AlbumGenres { get; set; }
        public ICollection<SongGenre> SongGenres { get; set; }
    }
}

ViewModels/GenreViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MelodyMusicLibrary.ViewModels
{
    public class GenreViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }
        public IFormFile ImageFile { get; set; } 
    }

}

Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MelodyMusicLibrary.Data;
using MelodyMusicLibrary.Models;
using MelodyMusicLibrary.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace MelodyMusicLibrary.Controllers
{
    public class AlbumsController : Controller
    {
        private readonly MelodyContext _context;

        public AlbumsController(MelodyContext context)
        {
            _context = context;
        }

        // GET: Albums
        public async Task<IActionResult> Index(AlbumSearchViewModel searchModel)
        {
            // Query albums from database
            var query = _context.Album
                                .Include(a => a.AlbumArtists).ThenInclude(aa => aa.Artist)
                                .Include(a => a.AlbumGenres).ThenInclude(ag => ag.Genre)
                                .AsQueryable();

            // Apply filters
            if (!string.IsNullOrEmpty(searchModel.Title))
            {
                query = query.Where(a => a.Title.Contains(searchModel.Title));
            }

            if (!string.IsNullOrEmpty(searchModel.Artist))
            {
                query = query.Where(a => a.AlbumArtists.Any(aa => aa.Artist.Name.Contains(searchModel.Artist)));
            }

            if (!string.IsNullOrEmpty(searchModel.Genre))
            {
                query = query.Where(a => a.AlbumGenres.Any(ag => ag.Genre.Name.Contains(searchModel.Genre)));
            }

            // Populate SelectList for genres
            var genres = await _context.Genre.OrderBy(g => g.Name)
                                              .Select(g => new SelectListItem
                                              {
                                                  Value = g.Name,
                                                  Text = g.Name
                                              }).ToListAsync();
            genres.Insert(0, new SelectListItem { Value = "", Text = "Genre" });
            searchModel.Genres = new SelectList(genres, "Value", "Text");

            // Populate SelectList for artists
            var artists = await _context.Artist.OrderBy(a => a.Name)
                                                .Select(a => new SelectListItem
                                                {
                                                    Value = a.Name,
                                                    Text = a.Name
                                                }).ToListAsync();
            artists.Insert(0, new SelectListItem { Value = "", Text = "Artist" });
            searchModel.Artists = new SelectList(artists, "Value", "Text");

            // Retrieve albums matching the query
            searchModel.Albums = await query.ToListAsync();

            return View(searchModel);
        }

        // GET: Albums/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Album
            .Include(a => a.AlbumArtists)
                .ThenInclude(aa => aa.Artist)
            .Include(a => a.AlbumGenres)
                .ThenInclude(ag => ag.Genre)
            .Include(a => a.Songs)
            .FirstOrDefaultAsync(a => a.Id == id);
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        // GET: Albums/Create
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            var artists = await _context.Artist.OrderBy(a => a.Name)
                                               .Select(a => new SelectListItem
                                               {
                                                   Value = a.Id.ToString(),
                                                   Text = a.Name
                                               }).ToListAsync();

            var genres = await _context.Genre.OrderBy(g => g.Name)
                                             .Select(g => new SelectListItem
                                             {
                                                 Value = g.Id.ToString(),
                                                 Text = g.Name
                                             }).ToListAsync();

            var viewModel = new AlbumCreateViewModel
            {
                ArtistList = new SelectList(artists, "Value", "Text"),
                GenresList = new SelectList(genres, "Value", "Text")
            };

            return View(viewModel);
        }

        // POST: Albums/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AlbumCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                // Map ViewModel to Album model
                var album = new Album
                {
                    Title = viewModel.Title,
                    ReleaseDate = viewModel.ReleaseDate,
                    CoverUrl = viewModel.CoverUrl
                };

                // Add selected artists to the album
                if (viewModel.SelectedArtist != null)
                {
                    foreach (var artistId in viewModel.SelectedArtist)
                    {
                        album.AlbumArtists.Add(new AlbumArtist { ArtistId = artistId });
                    }
                }

                // Add selected genres to the album
                if (viewModel.SelectedGenres != null)
                {
                    foreach (var genreId in viewModel.SelectedGenres)
                    {
                        album.AlbumGenres.Add(new AlbumGenre { GenreId = genreId });
                    }
                }

                _context.Add(album);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // If model state is not valid, re-render the view with errors
            viewModel.ArtistList = new SelectList(await _context.Artist.OrderBy(a => a.Name)
                                                                       .Select(a => new SelectListItem
                                                                       {
                                                                           Value = a.Id.ToString(),
                                                                           Text = a.Name
                                                                       }).ToListAsync(), "Value", "Text");

            viewModel.GenresList = new SelectList(await _context.Genre.OrderBy(g => g.Name)
                                                                     .Select(g => new SelectListItem
                                                                     {
                                                                         Value = g.Id.ToString(),
                                                                         Text = g.Name
                                                                     }).ToListAsync(), "Value", "Text");

            return View(viewModel);
        }

        // GET: Albums/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Album.Where(a => a.Id == id)
                .Include(a => a.AlbumArtists)
                .Include(a => a.AlbumGenres)
                .FirstOrDefaultAsync();
            if (album == null)
            {
                return NotFound();
            }

            var artists = _context.Artist.AsEnumerable().OrderBy(s => s.Name);
            var genres = _context.Genre.AsEnumerable().OrderBy(s => s.Name);

            AlbumEditViewModel viewmodel = new()
            {
                Album = album,
                ArtistList = new MultiSelectList(artists, "Id", "Name"),
                SelectedArtist = album.AlbumArtists.Select(aa => aa.ArtistId),
                GenresList = new MultiSelectList(genres, "Id", "Name"),
                SelectedGenres = album.AlbumGenres.Select(ag => ag.GenreId)
            };
            return View(viewmodel);
        }



        // POST: Albums/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, AlbumEditViewModel viewmodel)
        {
            if (id != viewmodel.Album.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var albumToUpdate = await _context.Album
                        .Include(a => a.AlbumArtists)
                        .Include(a => a.AlbumGenres)
                        .FirstOrDefaultAsync(a => a.Id == id);

                    if (albumToUpdate == null)
                    {
                        return NotFound();
                    }

                    // Update album details
                    albumToUpdate.Title = viewmodel.Album.Title;
                    albumToUpdate.ReleaseDate = viewmodel.Album.ReleaseDate;
                    albumToUpdate.CoverUrl = viewmodel.Album.CoverUrl;

                    // Update AlbumArtists
                    var newArtistList = viewmodel.SelectedArtist ?? Enumerable.Empty<int>();

Controllers/GenresController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MelodyMusicLibrary.Models;
using MelodyMusicLibrary.ViewModels;
using System;
using System.IO;
using System.Threading.Tasks;
using System.Linq;
using MelodyMusicLibrary.Data;

public class GenresController : Controller
{
    private readonly IWebHostEnvironment _webHostEnvironment;
    private readonly MelodyContext _context; // Assuming you have a DbContext for your application

    public GenresController(IWebHostEnvironment webHostEnvironment, MelodyContext context)
    {
        _webHostEnvironment = webHostEnvironment;
        _context = context;
    }

    // GET: Genres
    public IActionResult Index()
    {
        var genres = _context.Genre.ToList();
        return View(genres);
    }

    // GET: Genres/Details/5
    public IActionResult Details(int id)
    {
        var genre = _context.Genre.FirstOrDefault(g => g.Id == id);
        if (genre == null)
        {
            return NotFound();
        }
        return View(genre);
    }

    // GET: Genres/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Genres/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(GenreViewModel model)
    {

        if (ModelState.IsValid)
        {
            string fileName = model.Name;
            await SaveImageFile(model.ImageFile, fileName);

            Genre genre = new Genre
            {
                Name = model.Name,
                ImageUrl = fileName != null ? "/images/genres/" + fileName : null
            };

            _context.Add(genre);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(model);
    }

    // GET: Genre/Edit/5
    public IActionResult Edit(int id)
    {
        var genre = _context.Genre.FirstOrDefault(g => g.Id == id);
        if (genre == null)
        {
            return NotFound();
        }

        GenreViewModel model = new GenreViewModel
        {
            Id = genre.Id,
            Name = genre.Name,
        };

        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, GenreViewModel model)
    {
        if (id != model.Id)
        {
            return NotFound();
        }

        // Check the current state of the genre
        var genre = await _context.Genre.FindAsync(id);
        if (genre == null)
        {
            return NotFound();
        }

        // Check if ModelState is valid
        if (ModelState.IsValid)
        {
            // Update only if ImageFile is provided or if there is no current image
            if (model.ImageFile != null)
            {
                string fileName = model.Name; // Or any logic to generate a unique file name
                await SaveImageFile(model.ImageFile, fileName);
                genre.ImageUrl = "/images/genres/" + fileName;
            }

            genre.Name = model.Name;

            _context.Update(genre);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        else
        {
            // Log model state errors
            foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
            {
                Console.WriteLine($"Error: {error.ErrorMessage}");
            }
        }

        // If ModelState is not valid, return the view with errors
        return View(model);
    }



    // GET: Genres/Delete/5
    public IActionResult Delete(int id)
    {
        var genre = _context.Genre.FirstOrDefault(g => g.Id == id);
        if (genre == null)
        {
            return NotFound();
        }

        return View(genre);
    }

    // POST: Genres/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var genre = _context.Genre.FirstOrDefault(g => g.Id == id);
        if (genre == null)
        {
            return NotFound();
        }

        _context.Genre.Remove(genre);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private async Task<string> SaveImageFile(IFormFile imageFile, string genreName)
    {
        if (imageFile == null || imageFile.Length == 0)
        {
            return null;
        }

        string wwwRootPath = _webHostEnvironment.WebRootPath;
        string fileName = genreName + Path.GetExtension(imageFile.FileName);
        string filePath = Path.Combine(wwwRootPath, "images", "genres", fileName);

        using (var fileStream = new FileStream(filePath, FileMode.Create))
        {
            await imageFile.CopyToAsync(fileStream);
        }

        return fileName;
    }

}

Views/Genres/Create.cshtml
@model MelodyMusicLibrary.ViewModels.GenreViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create Genre</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label">Upload Image</label>
                <input asp-for="ImageFile" type="file" class="form-control" onchange="previewImage(event)" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <img id="imagePreview" src="#" alt="Image Preview" class="img-thumbnail bg-dark text-white" style="max-width: 100%; height: auto;" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        function previewImage(event) {
            const input = event.target;
            const reader = new FileReader();
            reader.onload = function () {
                const imagePreview = document.getElementById('imagePreview');
                imagePreview.src = reader.result;
            }
            if (input.files && input.files[0]) {
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

Views/Genres/Delete.cshtml
@model MelodyMusicLibrary.Models.Genre

@{
    ViewData["Title"] = "Delete";
}

<h1 class="table-title">Delete</h1>

<h3 class="text-light">Are you sure you want to delete this genre?</h3>
<div>
    <hr />
    <div class="container">
        <h3 class="table-title">Genre Details</h3>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>

        <form asp-action="Delete" class="m-3">
            <input type="hidden" asp-for="Id" />
            <button type="submit" class="btn btn-outline-danger rounded-pill px-3 py-2">Delete</button> |
            <a asp-action="Index" class="btn btn-outline-secondary rounded-pill px-3 py-2">Back to List</a>
        </form>
    </div>
</div>

Views/Genres/Details.cshtml
@model MelodyMusicLibrary.Models.Genre

@{
    ViewData["Title"] = "Details";
}

<div class="container mt-5">
    <h1 class="table-title">Genre Details</h1>
    <div class="row">
        <div class="col-lg-3">
            <div >
                <img src="~/images/genres/@(Model.Name).png" alt="Genre Image" class="bg-dark text-white"  />
            </div>
        </div>
        <div class="col-md-8">
            <dl class="row">
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Name)
                </dd>
            </dl>
            <div>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-success rounded-pill px-3 py-2">Edit</a>
                }
                <a asp-action="Index" class="btn btn-outline-secondary rounded-pill px-3 py-2">Back to List</a>
            </div>
        </div>
    </div>
</div>

Views/Genres/Edit.cshtml
@model MelodyMusicLibrary.ViewModels.GenreViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Genre</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="Id" value="@Model.Id" />

            <div class="form-group">
                <label for="Name" class="control-label">Name</label>
                <input id="Name" name="Name" value="@Model.Name" class="form-control bg-dark text-white" />
                <span class="text-danger">@Html.ValidationMessageFor(m => m.Name)</span>
            </div>

            <div class="form-group">
                <label for="ImageFile" class="control-label">Upload Image</label>
                <input id="ImageFile" name="ImageFile" type="file" class="form-control" onchange="previewImage(event)" />
                <span class="text-danger">@Html.ValidationMessageFor(m => m.ImageFile)</span>
            </div>

            <div class="form-group">
                <div class="row align-items-center">
                    <div class="col-auto">
                        <label class="control-label">Current Image</label>
                        <div>
                            <img src="~/images/genres/@(Model.Name).png" alt="Current Image" class="img-thumbnail bg-dark text-white" style="max-width: 100%; height: auto;" />
                        </div>
                    </div>
                    <div class="col">
                        <i class="fas fa-arrow-right fa-3x text-muted"></i>
                    </div>
                    <div class="col-6">
                        <label class="control-label">New Image</label>
                        <div>
                            <img id="imagePreview" src="#" alt="New Image Preview" class="img-thumbnail bg-dark text-white" style="max-width: 100%; height: auto;" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-outline-warning">Save</button>
                <a asp-action="Index" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        function previewImage(event) {
            const input = event.target;
            const reader = new FileReader();
            reader.onload = function () {
                const imagePreview = document.getElementById('imagePreview');
                imagePreview.src = reader.result;

                // Check if there is already an image present
                const currentImage = document.getElementById('currentImage');
                if (currentImage.src !== "") {
                    document.getElementById('ImageFile').removeAttribute('required');
                } else {
                    document.getElementById('ImageFile').setAttribute('required', 'required');
                }
            }
            if (input.files && input.files[0]) {
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

Views/Genres/Index.cshtml
@model IEnumerable<MelodyMusicLibrary.Models.Genre>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml"; // Assuming you have a shared layout file
}

<div class="container mt-5">
    <div class="row mb-4 d-flex align-items-center justify-content-between">
        <div class="col d-inline-flex justify-content-md-start">
            <h1 class="table-title">Genres</h1>
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                <div style="margin-left: 1rem; align-content: center;">
                    <a asp-action="Create" class="rounded-pill btn btn-outline-warning">+</a>
                </div>
            }
        </div>
    </div>

    <table class="table table-dark table-hover custom-table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>Image</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-controller="Genres" asp-action="Details" asp-route-id="@item.Id" class="btn-outline-warning text-decoration-none p-1" style="border-radius: 20px">
                            @Html.DisplayFor(modelItem => item.Name)
                        </a>
                    </td>
                    <td>
                        <a asp-controller="Albums" asp-action="GenreDetails" asp-route-id="@item.Id">
                            <div class="genre-image-container">
                                <img src="~/images/genres/@(item.Name).png" alt="@item.Name" class="img-thumbnail bg-dark" />
                            </div>
                        </a>
                    </td>
                    <td>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-success btn-sm rounded-pill px-3 py-2">Edit</a>
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger btn-sm rounded-pill px-3 py-2 ml-1">Delete</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".js-example-basic-multiple").select2();
        });
    </script>
}