Models/Artist.cs
namespace MelodyMusicLibrary.Models
{
    public class Artist
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ICollection<AlbumArtist> AlbumArtists { get; set; }
        public ICollection<SongArtist> SongArtists { get; set; }
    }
}

ViewModels/ArtistViewModel.cs
namespace MelodyMusicLibrary.ViewModels
{
    public class ArtistViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }
    }
}

Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MelodyMusicLibrary.Data;
using MelodyMusicLibrary.Models;
using MelodyMusicLibrary.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace MelodyMusicLibrary.Controllers
{
    public class AlbumsController : Controller
    {
        private readonly MelodyContext _context;

        public AlbumsController(MelodyContext context)
        {
            _context = context;
        }

        // GET: Albums
        public async Task<IActionResult> Index(AlbumSearchViewModel searchModel)
        {
            // Query albums from database
            var query = _context.Album
                                .Include(a => a.AlbumArtists).ThenInclude(aa => aa.Artist)
                                .Include(a => a.AlbumGenres).ThenInclude(ag => ag.Genre)
                                .AsQueryable();

            // Apply filters
            if (!string.IsNullOrEmpty(searchModel.Title))
            {
                query = query.Where(a => a.Title.Contains(searchModel.Title));
            }

            if (!string.IsNullOrEmpty(searchModel.Artist))
            {
                query = query.Where(a => a.AlbumArtists.Any(aa => aa.Artist.Name.Contains(searchModel.Artist)));
            }

            if (!string.IsNullOrEmpty(searchModel.Genre))
            {
                query = query.Where(a => a.AlbumGenres.Any(ag => ag.Genre.Name.Contains(searchModel.Genre)));
            }

            // Populate SelectList for genres
            var genres = await _context.Genre.OrderBy(g => g.Name)
                                              .Select(g => new SelectListItem
                                              {
                                                  Value = g.Name,
                                                  Text = g.Name
                                              }).ToListAsync();
            genres.Insert(0, new SelectListItem { Value = "", Text = "Genre" });
            searchModel.Genres = new SelectList(genres, "Value", "Text");

            // Populate SelectList for artists
            var artists = await _context.Artist.OrderBy(a => a.Name)
                                                .Select(a => new SelectListItem
                                                {
                                                    Value = a.Name,
                                                    Text = a.Name
                                                }).ToListAsync();
            artists.Insert(0, new SelectListItem { Value = "", Text = "Artist" });
            searchModel.Artists = new SelectList(artists, "Value", "Text");

            // Retrieve albums matching the query
            searchModel.Albums = await query.ToListAsync();

            return View(searchModel);
        }

        // GET: Albums/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Album
            .Include(a => a.AlbumArtists)
                .ThenInclude(aa => aa.Artist)
            .Include(a => a.AlbumGenres)
                .ThenInclude(ag => ag.Genre)
            .Include(a => a.Songs)
            .FirstOrDefaultAsync(a => a.Id == id);
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        // GET: Albums/Create
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            var artists = await _context.Artist.OrderBy(a => a.Name)
                                               .Select(a => new SelectListItem
                                               {
                                                   Value = a.Id.ToString(),
                                                   Text = a.Name
                                               }).ToListAsync();

            var genres = await _context.Genre.OrderBy(g => g.Name)
                                             .Select(g => new SelectListItem
                                             {
                                                 Value = g.Id.ToString(),
                                                 Text = g.Name
                                             }).ToListAsync();

            var viewModel = new AlbumCreateViewModel
            {
                ArtistList = new SelectList(artists, "Value", "Text"),
                GenresList = new SelectList(genres, "Value", "Text")
            };

            return View(viewModel);
        }

        // POST: Albums/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AlbumCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                // Map ViewModel to Album model
                var album = new Album
                {
                    Title = viewModel.Title,
                    ReleaseDate = viewModel.ReleaseDate,
                    CoverUrl = viewModel.CoverUrl
                };

                // Add selected artists to the album
                if (viewModel.SelectedArtist != null)
                {
                    foreach (var artistId in viewModel.SelectedArtist)
                    {
                        album.AlbumArtists.Add(new AlbumArtist { ArtistId = artistId });
                    }
                }

                // Add selected genres to the album
                if (viewModel.SelectedGenres != null)
                {
                    foreach (var genreId in viewModel.SelectedGenres)
                    {
                        album.AlbumGenres.Add(new AlbumGenre { GenreId = genreId });
                    }
                }

                _context.Add(album);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // If model state is not valid, re-render the view with errors
            viewModel.ArtistList = new SelectList(await _context.Artist.OrderBy(a => a.Name)
                                                                       .Select(a => new SelectListItem
                                                                       {
                                                                           Value = a.Id.ToString(),
                                                                           Text = a.Name
                                                                       }).ToListAsync(), "Value", "Text");

            viewModel.GenresList = new SelectList(await _context.Genre.OrderBy(g => g.Name)
                                                                     .Select(g => new SelectListItem
                                                                     {
                                                                         Value = g.Id.ToString(),
                                                                         Text = g.Name
                                                                     }).ToListAsync(), "Value", "Text");

            return View(viewModel);
        }

        // GET: Albums/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Album.Where(a => a.Id == id)
                .Include(a => a.AlbumArtists)
                .Include(a => a.AlbumGenres)
                .FirstOrDefaultAsync();
            if (album == null)
            {
                return NotFound();
            }

            var artists = _context.Artist.AsEnumerable().OrderBy(s => s.Name);
            var genres = _context.Genre.AsEnumerable().OrderBy(s => s.Name);

            AlbumEditViewModel viewmodel = new()
            {
                Album = album,
                ArtistList = new MultiSelectList(artists, "Id", "Name"),
                SelectedArtist = album.AlbumArtists.Select(aa => aa.ArtistId),
                GenresList = new MultiSelectList(genres, "Id", "Name"),
                SelectedGenres = album.AlbumGenres.Select(ag => ag.GenreId)
            };
            return View(viewmodel);
        }



        // POST: Albums/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, AlbumEditViewModel viewmodel)
        {
            if (id != viewmodel.Album.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var albumToUpdate = await _context.Album
                        .Include(a => a.AlbumArtists)
                        .Include(a => a.AlbumGenres)
                        .FirstOrDefaultAsync(a => a.Id == id);

                    if (albumToUpdate == null)
                    {
                        return NotFound();
                    }

                    // Update album details
                    albumToUpdate.Title = viewmodel.Album.Title;
                    albumToUpdate.ReleaseDate = viewmodel.Album.ReleaseDate;
                    albumToUpdate.CoverUrl = viewmodel.Album.CoverUrl;

                    // Update AlbumArtists
                    var newArtistList = viewmodel.SelectedArtist ?? Enumerable.Empty<int>();

Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MelodyMusicLibrary.Data;
using MelodyMusicLibrary.Models;
using MelodyMusicLibrary.ViewModels;

namespace MelodyMusicLibrary.Controllers
{
    public class ArtistsController : Controller
    {
        private readonly MelodyContext _context;

        public ArtistsController(MelodyContext context)
        {
            _context = context;
        }

        // GET: Artists
        public async Task<IActionResult> Index()
        {
            return View(await _context.Artist.ToListAsync());
        }

        // GET: Artists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artist
                .FirstOrDefaultAsync(m => m.Id == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // GET: Artists/Create
        public IActionResult Create()
        {
            return View(new ArtistViewModel());
        }

        // POST: Artists/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ArtistViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var artist = new Artist
                {
                    Name = viewModel.Name,
                    Description = viewModel.Description
                };

                _context.Add(artist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        // GET: Artists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artist.FindAsync(id);
            if (artist == null)
            {
                return NotFound();
            }

            var viewModel = new ArtistViewModel
            {
                Id = artist.Id,
                Name = artist.Name,
                Description = artist.Description
            };

            return View(viewModel);
        }

        // POST: Artists/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ArtistViewModel viewModel)
        {
            if (id != viewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var artist = await _context.Artist.FindAsync(id);
                    artist.Name = viewModel.Name;
                    artist.Description = viewModel.Description;

                    _context.Update(artist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArtistExists(viewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        // GET: Artists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artist
                .FirstOrDefaultAsync(m => m.Id == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // POST: Artists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artist = await _context.Artist.FindAsync(id);
            if (artist != null)
            {
                _context.Artist.Remove(artist);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArtistExists(int id)
        {
            return _context.Artist.Any(e => e.Id == id);
        }
    }
}

Views/Artists/Create.cshtml
@model MelodyMusicLibrary.ViewModels.ArtistViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label">Name</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label">Description</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Create</button>
                <a asp-action="Index" class="btn btn-secondary ml-2">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".js-example-basic-multiple").select2();
        });
    </script>
}

Views/Artists/Delete.cshtml
@model MelodyMusicLibrary.Models.Artist

@{
    ViewData["Title"] = "Delete";
}

<h1 class="table-title">Delete</h1>

<h3 class="text-light">Are you sure you want to delete this artist?</h3>
<div>
    <hr />
    <div class="container">
        <h3 class="table-title">Artist Details</h3>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>

        <form asp-action="Delete" class="m-3">
            <input type="hidden" asp-for="Id" />
            <button type="submit" class="btn btn-outline-danger rounded-pill px-3 py-2">Delete</button> |
            <a asp-action="Index" class="btn btn-outline-secondary rounded-pill px-3 py-2">Back to List</a>
        </form>
    </div>
</div>

Views/Artists/Details.cshtml
@model MelodyMusicLibrary.Models.Artist

@{
    ViewData["Title"] = "Artist Details";
}

<div class="container mt-5">
    <h1 class="table-title">Artist Details</h1>
    <div class="row">
        <div class="col-lg-3">
            <div>
                <img src="~/images/artists/@(Model.Name).png" alt="Artist Image" class="bg-dark text-white" />
            </div>
        </div>
        <div class="col-md-8">
            <dl class="row">
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </dl>
            <div>
                <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-success rounded-pill px-3 py-2">Edit</a>
                <a asp-action="Index" class="btn btn-outline-secondary rounded-pill px-3 py-2">Back to List</a>
            </div>
        </div>
    </div>
</div>

Views/Artists/Edit.cshtml
@model MelodyMusicLibrary.ViewModels.ArtistViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Name" class="control-label">Name</label>
                <input asp-for="Name" class="form-control bg-dark text-white" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label">Description</label>
                <textarea asp-for="Description" rows="5" class="form-control bg-dark text-white"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Save</button>
                <a asp-action="Index" class="btn btn-secondary ml-2">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".js-example-basic-multiple").select2();
        });
    </script>
}

Views/Artists/Index.cshtml
@model IEnumerable<MelodyMusicLibrary.Models.Artist>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml"; // Assuming you have a shared layout file
}

<div class="container mt-5">
    <div class="row mb-4 d-flex align-items-center justify-content-between">
        <div class="col d-inline-flex justify-content-md-start">
            <h1 class="table-title">Artists</h1>
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
            <div style="margin-left:1rem; align-content:center;">
                <a asp-action="Create" class="rounded-pill btn btn-outline-warning">+</a>
            </div>
                        }
        </div>
        @*<div class="col-5">
        <form asp-controller="Artists" asp-action="Index" method="get" class="d-inline-flex justify-content-center align-items-center">
        <div class="form-group mr-2">
        <input type="text" asp-for="Name" placeholder="Search by Name" class="form-control" />
        </div>
        <div class="form-group mr-2">
        <input type="text" asp-for="Description" placeholder="Search by Description" class="form-control" />
        </div>
        <div class="form-group">
        <input type="submit" value="Filter" class="btn btn-primary" />
        </div>
        </form>
        </div>*@
    </div>

    <table class="table table-dark table-hover custom-table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.Description)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-controller="Albums" asp-action="Index" asp-route-artist="@item.Name" class="btn-outline-warning text-decoration-none p-1 text-decoration-underline d-inline-block" style="border-radius:20px; ">
                            @Html.DisplayFor(modelItem => item.Name)
                        </a>
                    </td>
                    <td style="width:70%">@Html.DisplayFor(modelItem => item.Description)</td>
                    <td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-success btn-sm rounded-pill px-3 py-2">Edit</a>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-info btn-sm rounded-pill px-3 py-2 ml-1">Details</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger btn-sm rounded-pill px-3 py-2 ml-1">Delete</a>
                    }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".js-example-basic-multiple").select2();
        });
    </script>
}